### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by KristerV** [discourse/discourse-meteor#1]
hi. I get that installing the plugin can be done by following [the official guide](https://meta.discourse.org/t/install-a-plugin/19157), but once installed how do I use this thing? How does the end user use this?

Like is this what I expect: user is logged into my meteor app - clicking on a link to a discourse forum will log the person into the forum?

**Comment by KristerV** [comment]
oh right. this is the discourse Oauth2 plugin for just www.meteor.com, right? I can't use this in my own app?

**Comment by discoursebuild** [comment]
I think so, you are going to need the meteor private keys to be able to use
it in your site.

**Comment by KristerV** [comment]
ok
